CREATE TABLE IF NOT EXISTS user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    email TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS user_feed (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER,
    feed_id INTEGER,
    FOREIGN KEY(user_id) REFERENCES ApplicationUser(id),
    FOREIGN KEY(feed_id) REFERENCES Feed(id)
);

CREATE TABLE IF NOT EXISTS feed (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    url TEXT NOT NULL
);
